# Generated by Django 6.0.2 on 2026-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='file',
        ),
    ]
